- RT_num_11_plus_pts_wins_L7G
- Num_Players_15plus_PPG_L8G_RT 
- RT_AVG_PTdiff_LG
- BL_AVG_L3G_RT
- Num_Players_15plus_PPG_L8G_RT
- FG_PCT_LG_RT
- 3PT_PCT_L2G_RT
- TS_PCT_LG_RT
- PPG_AVG_L9G_RT
- Num_Players_2plus_BL_L4G_RT
- Num_Players_2plus_ST_L3G_RT
- APG_AVG_L5G_RT  
- RT_AVG_Loss_PTdiff_L4G
- Num_Players_5plus_APG_LG_RT 
- BL_AVG_L4G_RT
- ST_AVG_L5G_RT
- FG_PCT_L4G_RT 
- ST_AVG_L9G_RT
- TS_PCT_L4G_RT 
- RT_AVG_Win_PTdiff_L10G
- RT_num_11_plus_pts_wins_L8G
- TOT_AVG_L6G_RT
- Num_Players_15plus_PPG_L5G_RT  
- OEFF_L2G_RT
- RT_AVG_Win_PTdiff_L10G
- PPG_AVG_L4G_RT
- PACE_L2G_RT
- TS_PCT_L8G_RT
- BL_AVG_L8G_RT
- Num_Players_1plus_TO_L3G_RT
- DEFF_L10G_RT 
- OEFF_L10G_RT
- FT_PCT_L4G_RT
- Num_Players_1plus_ST_L8G_RT
- RT_AVG_Win_PTdiff_L8G
- Num_Players_20plus_PPG_L8G_RT
- Num_Players_5plus_APG_L4G_RT
- Num_Players_3plus_TO_L2G_RT
- RT_cnt_wins_6_plus_L3G
- OEFF_LG_RT
- Num_Players_5plus_TOT_L4G_RT
- PPG_AVG_L8G_RT
- RT_AVG_PTdiff_L4G
- FT_PCT_LG_RT
- RT_cnt_loss_6_plus_L10G
- Num_Players_2plus_BL_L7G_RT
- Num_Players_3plus_TO_LG_RT
- 3PT_PCT_L9G_RT
- RT_Num_Wins_L9G
- Num_Players_2plus_ST_L8G_RT
- HT_num_11_plus_pts_wins_L7G 
- Num_Players_15plus_PPG_L8G_HT 
- HT_AVG_PTdiff_LG
- BL_AVG_L3G_HT 
- Num_Players_15plus_PPG_L8G_HT
- FG_PCT_LG_HT
- 3PT_PCT_L2G_HT
- TS_PCT_LG_HT
- PPG_AVG_L9G_HT
- Num_Players_2plus_BL_L4G_HT
- Num_Players_2plus_ST_L3G_HT
- APG_AVG_L5G_HT
- HT_AVG_Loss_PTdiff_L4G
- Num_Players_5plus_APG_LG_HT
- BL_AVG_L4G_HT
- ST_AVG_L5G_HT
- FG_PCT_L4G_HT
- ST_AVG_L9G_HT
- TS_PCT_L4G_HT
- HT_AVG_Win_PTdiff_L10G
- HT_num_11_plus_pts_wins_L8G
- TOT_AVG_L6G_HT
- Num_Players_15plus_PPG_L5G_HT
- OEFF_L2G_HT
- HT_AVG_Win_PTdiff_L10G
- PPG_AVG_L4G_HT
- PACE_L2G_HT
- TS_PCT_L8G_HT
- BL_AVG_L8G_HT 
- Num_Players_1plus_TO_L3G_HT
- DEFF_L10G_HT
- OEFF_L10G_HT
- FT_PCT_L4G_HT
- Num_Players_1plus_ST_L8G_HT
- HT_AVG_Win_PTdiff_L8G
- Num_Players_20plus_PPG_L8G_HT
- Num_Players_5plus_APG_L4G_HT
- Num_Players_3plus_TO_L2G_HT
- HT_cnt_wins_6_plus_L3G
- OEFF_LG_HT
- Num_Players_5plus_TOT_L4G_HT
- PPG_AVG_L8G_HT
- HT_AVG_PTdiff_L4G
- FT_PCT_LG_HT
- HT_cnt_loss_6_plus_L10G
- Num_Players_2plus_BL_L7G_HT
- Num_Players_3plus_TO_LG_HT
- 3PT_PCT_L9G_HT
- HT_Num_Wins_L9G
- Num_Players_2plus_ST_L8G_HT